@startuml
skin rose
title Распределенное выполнение АСО
start
  :Инициализация параметров;
  :Распределение муравьев по процессам(клиентам);
  while (Есть ещё итерации?) is (да)
    :Запуск процессов для поиска решений;
    note right: Возможно N-процессов(клиентов) 
    fork 
      :Получение феромона;
      :Поиск решения;
      :Отправка найденого решения;
    fork again
      :Получение феромона;
      :Поиск решения;
      :Отправка найденого решения;
    end fork
     if ( Значение N-клиента > глобального значения?) then (да) 
        :Обновление лучшего значения;
        :Обновление лучшего набора рюкзака;
      else (нет)
      endif
    :Обновление глобального феромона;
  endwhile (нет)
end
@enduml