 @startuml ElDoc

autonumber
skin rose
scale 0.9
title Распределенный алгоритм муравьиной колонии (ACO)
actor User
participant Server
participant Client

User -> Server : Запуск сервера
activate Server
Server -> Server : Чтение 'сonfig'
Server -> Server : Создание сокетов
Server -> Server : Распределение муравьев для клиентов
Server -> Client : Удаленное включение процесса
activate Client

Client --> Server : Подключение к портам
deactivate Client

Server -> Server : Подтверждение сокетов

Server ->> Client: Отправка начальных данных
activate Client

Client -->> Server: Подтверждение принятых данных
deactivate Client


loop Итерация колонии
Server -> Client: Отправка феромонов
activate Client
Client -> Client: выполнение алгоритма
Client -->> Server: Возврат локальных результатов (лучшее решение)
Server -> Server: Обновление феромонов
Server -> Server: Обновление лучшего результа
Server ->> Client: Отправка обновленных феремонов
deactivate Client
end

Server -->> User : Вывод результатов
deactivate Server
@enduml