 @startuml ElDoc

autonumber
title Распределенный алгоритм
actor User
participant Server
participant Client

User -> Server : Запуск сервера
activate Server
Server -> Server : Чтение 'сonfig'
Server -> Server : Создание сокетов
Server -> Client : Удаленное включение процесса
activate Client

Client --> Server : Подключение к портам
deactivate Client

Server ->> Client: Отправка начальных данных
activate Client

Client -->> Server: Подтверждение принятых данных
deactivate Client


loop итерация колонии
Server ->> Client: Отправка феромонов
activate Client
Client -> Client: выполнение алгоритма
Client -->> Server: Возврат локальных результатов (лучшее решение, решения)
Server -> Server: Обновление феромонов
Server ->> Client: Отправка обновленных феремонов
deactivate Client
end

Server --> User : Вывод результатов
deactivate Server
@enduml